# Generated by Django 3.1.7 on 2021-05-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcards',
            old_name='word',
            new_name='code',
        ),
    ]
